export { default as Navbar } from "./navbar.tsx";
export { default as CallToAction } from "./call-to-action.tsx";
export { default as Hero } from "./hero.tsx";
export { default as About } from "./about.tsx";
export { default as BlogHeadings } from "./blog.headings.tsx";
export { default as Product } from "./products.tsx";
export { default as SocialProof } from "./social.proof.tsx";
export { default as WorkProcess } from "./work.process.tsx";
export { default as Layout } from "./layout.tsx";
